export const GET_CUSTOMERS_PENDING = "GET_CUSTOMERS_PENDING";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_ERROR = "GET_CUSTOMERS_ERROR";
export const GET_CUSTOMERS_DELETE = "GET_CUSTOMERS_DELETE";
export const GET_CUSTOMERS_EDIT = "GET_CUSTOMERS_EDIT";
export const GET_CUSTOMERS_ADD = "GET_CUSTOMERS_ADD";